### ISSUE TITLE
Use MaterialDiscord as a base

### ISSUE THREAD

**Issue by TheOPtimal** [orblazer/discord-nordic#1]
[MaterialDiscord](https://github.com/CapnKitten/BetterDiscord/tree/master/Themes/Material-Discord) is an excellent BandagedBD theme that uses Google's [Material Design](https://material.io) as a base for a theme.

However, it also allows modification of the theme's base variables. I have tried to do this myself, however I didn't succeed because I don't have a good eye.

MaterialDiscord is also easier since it offers it's own, simplified variables for modification.

By the way, I love your theme but on the subject of Nord - MaterialDiscord is just an amazing cherry on top.

**Comment by orblazer** [comment]
Sorry, but this is talk to make an new theme, that repo is not here for that.

I can make themes on request but that is not free (because i need times to make it).
