### ISSUE TITLE
[BUG] Role Mentions are incorrectly colored

### ISSUE THREAD

**Issue by Derpitron** [orblazer/discord-nordic#10]
The role "10th Standard" Is supposed to be purple in color, the same as the purple rectangle I used to censor my name. 

I believe that in your 3.2.0 update, you had tried to fix user and channel mentions, but you also applied that custom coloring to role mentions.
![image](https://user-images.githubusercontent.com/46134462/149056223-fe007664-a56f-4022-8e36-6b41c748f9ad.png)

**Comment by orblazer** [comment]
This is not an bug from the theme, its from plugin `BetterRoleColors` https://github.com/rauenzi/BetterDiscordAddons/issues/397

**Comment by Derpitron** [comment]
Ahh, I see, sorry for the scare

**Comment by Derpitron** [comment]
Edit: my issue is not the same! Mentioning users has the default color regardless of whether BetterRoleColors is enabled or not, but mentioning *roles* uses the default color, which it should not. I had given an example in the attached picture, where the role "10th Standard" (This is a school server where the grades are divided into roles) should be purple, i.e the same color as my role (which is purple). but, this is not the case.

I have attached another example here, my role color is green, but the role mention is blue, even though it should be green in color.
![image](https://user-images.githubusercontent.com/46134462/149128929-e7da8ac5-cdbd-44f4-ade7-19ad16e2b127.png)

**Comment by orblazer** [comment]
Oh ok, i have think that is same with user :facepalm:
