### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tetrax-10** [orblazer/discord-nordic#13]
Could you fix these colors

![image](https://user-images.githubusercontent.com/75513645/192106125-411b3f46-0f58-4a76-8f2a-34457406e340.png)

**Versions (please complete the following information):**
 - Theme style : [Dark](https://orblazer.github.io/discord-nordic/base.css)
 - Theme version : v3.10.1
 - Discord Version : 1.1.1.0
 - BDD version : idk where to see it
 - Is `nordic.user.css` ?

**Comment by orblazer** [comment]
Hello,
What is the list of plugins, because i don't have the issue.

Thanks.

**Comment by Tetrax-10** [comment]
better discord not working lol

**Comment by orblazer** [comment]
> better discord not working lol

For theme it's work with version 1.7.0. And i can't reproduce the issue, so i think its due to an plugin or another theme.

**Comment by Tetrax-10** [comment]
its because of a update. i updated discord then saw this. most of them got this issue with diff themes.

**Comment by Tetrax-10** [comment]
How do i change those border colors to #2e3440? so the theme looks flat
![image](https://user-images.githubusercontent.com/75513645/219970311-199cb136-e731-4c5b-99a0-b464e085d7b4.png)
![image](https://user-images.githubusercontent.com/75513645/219970366-5c4094b8-408e-407d-a8a5-ee7ab915e8ab.png)

**Comment by Tetrax-10** [comment]
thx for making the theme flat
