### ISSUE TITLE
[FEAT] add back the github pages css

### ISSUE THREAD

**Issue by kristiankunc** [orblazer/discord-nordic#17]
**Is your feature request related to a problem? Please describe.**
There used to be a css hosted on gh pages which could be used to apply the theme as custom css rather than plugin (https://orblazer.github.io/discord-nordic/base.css) but that is not available anymore

**Describe the solution you'd like**
I'd like for this to be added back since I do not use betterdiscord but I still want to use this theme without having to copy the css files

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by orblazer** [comment]
hello,
you can simply import https://raw.githubusercontent.com/orblazer/discord-nordic/master/nordic.powercord.css or https://raw.githubusercontent.com/orblazer/discord-nordic/master/nordic.theme.css, right ?
