### ISSUE TITLE
[BUG] Tab focus ring is invisible

### ISSUE THREAD

**Issue by diogotcorreia** [orblazer/discord-nordic#18]
**Describe the bug**
Tab focus ring is invisible.

**To Reproduce**
Load the theme, go to a chat, press tab and then arrow up.
The messages will be hovered, but there is no focus ring.

**Expected behavior**
A colored focus ring should appear, just like on native Discord. See screenshots below.

I think the `var(--focus-primary)` variable is unset, hence it is not colored.

**Screenshots**

Original Discord:
![image](https://user-images.githubusercontent.com/7467891/205641904-e130fa48-73aa-4fc2-9c32-2fd695dffe0b.png)
![image](https://user-images.githubusercontent.com/7467891/205643906-01dfae2f-2325-448f-bbe0-47f3ac8e83b7.png)

Nordic theme:
![image](https://user-images.githubusercontent.com/7467891/205643429-0a23c9ab-55a3-4b1c-acb0-dcfb63988e77.png)

**Versions (please complete the following information):**
 - Theme style : Dark
 - Theme version : 4.3.0
 - Discord Version : Stable 162224 (e1ec9ed)
 - BDD version : None, using OpenASAR nightly
 - Is `nordic.user.css` ? No, `nordic.theme.css`

**Additional context**
Adding `--focus-primary: var(--brand-new-500)` to the customization section temporarily fixes the issue.

Probably related code:
https://github.com/orblazer/discord-nordic/blob/ad3b221897cfa614f4e456da814e48426b82103d/src/styles/colors/colors.scss#L115

**Comment by orblazer** [comment]
Hello,
Thanks for report the issue. This should fixed on the next release.
