### ISSUE TITLE
[BUG] Theme broken on Vencord and Replugged

### ISSUE THREAD

**Issue by RickMarijn** [orblazer/discord-nordic#19]
When importing the raw nordic.theme.css url into Vencord the theme doesn't look like the screenshots on the BetterDiscord website at all. It also doesn't work on Replugged.

**Comment by shimmerism** [comment]
same issue here

**Comment by orblazer** [comment]
Hello,
This should be fixed in `4.7.0` and using [nordic.vencord.css](https://github.com/orblazer/discord-nordic/blob/master/nordic.vencord.css).
