### ISSUE TITLE
Text selection color same as background color

### ISSUE THREAD

**Issue by MaximeDawn** [orblazer/discord-nordic#2]
**Theme version :** 2.7.4
**Discord Version :** Stable 77192 (f5037df)
**BDD version :** 0.3.5

**Steps to reproduce :** 

- Select text in chat
- Invisible !

Here's a gif to show : https://i.imgur.com/fQFEA9I.gif

**Comment by orblazer** [comment]
Update the theme to `2.8.1`  see if that is fixed

**Comment by MaximeDawn** [comment]
Yup fixed ! My bad if I missed updates ✋
