### ISSUE TITLE
[BUG] Black Text, Bad Contrast

### ISSUE THREAD

**Issue by Atlasim1** [orblazer/discord-nordic#23]
**Describe the bug**
Some text is completely black and lines no longer appear

**To Reproduce**
Use the theme

**Expected behavior**
Text to be readable and theme to not look broken

**Screenshots**
![image](https://user-images.githubusercontent.com/70275601/219479157-503f45e1-fe12-4ff0-997a-4c9bb6f8ecb4.png)

**Versions (please complete the following information):**
 - Theme style : Dark
 - Theme version : 4.8.0
 - Discord Version : Stable 174974 (d24986c)
 - BDD version : v1.8.4
 - Is `nordic.user.css` ? | what does this mean

**Comment by orblazer** [comment]
Hello, This is fix with `v4.8.1` and commit 38430a985682c96b0edfc1e01721c39fa85f9cc7.
