### ISSUE TITLE
[BUG] Discord woke up and chose violence, everything is broken, every single class has new random string to it

### ISSUE THREAD

**Issue by DarkReaper231** [orblazer/discord-nordic#24]
All the random strings are different. Probably due to the new color theme system for Nitro users. They probably had to redo a lot of the classes so they can actually use custom colors and that broke everything.

**Comment by orblazer** [comment]
Hello,
Sorry but i don't have nitro yet so i don't have any problem, could you provide some screens ?

**Comment by DarkReaper231** [comment]
> Hello, Sorry but i don't have nitro yet so i don't have any problem, could you provide some screens ?

I don't have nitro either

**Comment by orblazer** [comment]
Could you provide the "Discord Version" and "Better discord version" ? i think you use PTB or canary version (that i don't currently support).

**Comment by DarkReaper231** [comment]
> Could you provide the "Discord Version" and "Better discord version" ? i think you use PTB or canary version (that i don't currently support).

![image](https://user-images.githubusercontent.com/38611351/219900843-f5d36476-2c84-4480-9f8e-680a0261c90e.png)
![image](https://user-images.githubusercontent.com/38611351/219900878-05a99813-0801-4684-8bd1-81f2b253710d.png)

Maybe they are rolling out this feature meaning that not everyone has it at once?

**Comment by orblazer** [comment]
Hello,
Yes that is probably that because i have exactly same version, so as long i dont have that bugs i can't look for fix it, because even in canary or PTB versions i have this access.

**Comment by seiflotfy** [comment]
<img width="109" alt="Screenshot 2023-02-23 at 23 06 16" src="https://user-images.githubusercontent.com/117837/221051408-7b0a6d58-a38c-4941-8350-52994d78eaa8.png">
I am seeing this issue here... is this related?

**Comment by DarkReaper231** [comment]
> <img alt="Screenshot 2023-02-23 at 23 06 16" width="109" src="https://user-images.githubusercontent.com/117837/221051408-7b0a6d58-a38c-4941-8350-52994d78eaa8.png">
> 
> I am seeing this issue here... is this related?
> when I switch to settings it doesn't happen. <img alt="Screenshot 2023-02-23 at 23 32 36" width="465" src="https://user-images.githubusercontent.com/117837/221055407-f8a338fb-97b5-4752-8b94-d4ff29167c47.png">

No that's completely different problem

**Comment by DarkReaper231** [comment]
This somehow resolved itself so I am closing
