### ISSUE TITLE
Revert the serverlist bg color

### ISSUE THREAD

**Issue by zuzumi-f** [orblazer/discord-nordic#27]
**Is your feature request related to a problem? Please describe.**
The server list has a custom bg color instead of keep it transparent
![image](https://user-images.githubusercontent.com/79029257/233447192-3a128f5b-ce3f-4c7f-8227-ffe6928b624c.png)
![image](https://user-images.githubusercontent.com/79029257/233447265-fb44af27-9dc5-4f87-a97a-7c85518f5d99.png)

**Describe the solution you'd like**
Just delete this part or make an specific path if the scroller appear in another place. example: `div>.scroller-3X7KbA`
`.scroller-3X7KbA{background-color: var(--background-secondary-alt)!important;}`

**Comment by orblazer** [comment]
Hello,
This make side effect, and if yes could tell me where. If not explain why this change is useful ?

Thanks.

**Comment by zuzumi-f** [comment]
no side effects as far as I've seen
it is not "useful", rather consistent with the original discord colors. the theme has always kept the discord look (where the window bar and the serverlist are joined by the same color) except now that the serverlist has a lighter color and there is a quite visible curve in the corner.

**Comment by orblazer** [comment]
Hello,
You can add the below code until i fix the corner bug or i decide to revert the change of that color.

```css
.scroller-3X7KbA /* Servers sidebar */ {
  background-color: var(--background-tertiary) !important;
}
```

Thanks.

**Comment by orblazer** [comment]
Hello,
I close this issue because it's seem no longer an issue.
