### ISSUE TITLE
Support replugged

### ISSUE THREAD

**Issue by Asthowen** [orblazer/discord-nordic#29]
Hello! 
Would it be possible to make this theme directly compatible with replugged and add it to the theme store? 
I can potentially do a PR if you want.

**Comment by orblazer** [comment]
Hello,
Yes you can create the script for compile it, if you not i think i plan this in week or two.
After that i create the page on the store for upload it.

**Comment by natowb** [comment]
hey guys ive raised a PR which adds basic replugged support #31
