### ISSUE TITLE
[BUG] Colors broken on latest Discord update (240237)

### ISSUE THREAD

**Issue by diogotcorreia** [orblazer/discord-nordic#30]
**Describe the bug**
Colors in the uniform variant theme are no longer uniform.

**To Reproduce**
Update Discord to latest version as of 2023-10-25.

**Expected behavior**
Colors to be uniform.

**Screenshots**
![image](https://github.com/orblazer/discord-nordic/assets/7467891/6b5f5deb-c93e-4e0c-89f4-008b4915d202)
![image](https://github.com/orblazer/discord-nordic/assets/7467891/a1812ecc-968b-4a3f-8402-9c048ddea172)

**Versions (please complete the following information):**

- Theme style : Dark
- Theme version : 4.10.6
- Is `uniform` variant : Yes
- Discord Version : Stable 240237 (a1ba594) Host 0.0.31 x64 Linux 64-Bit (6.1.55)
- Client name & version (BetterDiscord, Powercord, etc) : OpenASAR (a8b07392808032f95ac3a7c5856e76d2619c91ae; unstable-2023-05-01)

**Additional context**
By looking at devtools, it appears that the class names have changed

**Comment by diogotcorreia** [comment]
Hey
I'm not sure if this is intended, but some colors are still not totally uniform, mainly in the server's channel list and in the users in the sidebar; and also in the user profile in DMs.
![image](https://github.com/orblazer/discord-nordic/assets/7467891/2219cdcc-c49c-4a09-a9cf-5e8bcd28a5ec)
![image](https://github.com/orblazer/discord-nordic/assets/7467891/ae690109-5de4-4d8b-bd6c-d86094a1931b)

**Comment by orblazer** [comment]
Hello,
Thanks for feedback and no its not intended for uniform version, i go to workaround this issue in few days.

**Comment by orblazer** [comment]
Hello,
Sorry for the late but the theme is now fixed.

Some places are probably not but i have plan to refactor all the code to handle theme options in new betterdiscord versions.

**Comment by diogotcorreia** [comment]
Seems to be working perfectly, thank you a lot for the hard work! Appreciated :)
