### ISSUE TITLE
[BUG] Uniform colors are not uniform

### ISSUE THREAD

**Issue by diogotcorreia** [orblazer/discord-nordic#34]
**Describe the bug**
It's me again :sweat_smile: 

After latest Discord update today, it seems like the uniform theme is broken again. The latest update doesn't seem to help.

I'm using https://raw.githubusercontent.com/orblazer/discord-nordic/v4.10.12/uniform/nordic.theme.css

**Screenshots**
![image](https://github.com/orblazer/discord-nordic/assets/7467891/2b42e779-7f34-4f67-9ece-6eb4a4aafef8)

**Versions (please complete the following information):**

- Theme style : Dark
- Theme version : 4.10.21
- Is `uniform` variant : Yes
- Discord Version : stable 303105 (1897d8a) Host 0.0.54 x64 Build Override: N/A Linux 64-bit (6.8.12)
- Client name & version (BetterDiscord, Vencord, etc) : OpenAsar 2024-01-13

Thank you for your efforts!

**Comment by orblazer** [comment]
Hello,
This should be fixed with las update.

**Comment by diogotcorreia** [comment]
It is indeed fixed, thank you so much!
