### ISSUE TITLE
[BUG] Discord Updated CSS Classes today, breaking some elements of this theme

### ISSUE THREAD

**Issue by Derpitron** [orblazer/discord-nordic#7]
**Describe the bug**
Certain UI elements have been reverted to the default Discord colors, possibly due to Discord updating the CSS.

Discord Mention has default yellow accent color
![image](https://user-images.githubusercontent.com/46134462/148934322-560f5e16-a8c9-4969-b0f4-f7a2b582f683.png)

Server/DM Search reverted to default Discord grey
![image](https://user-images.githubusercontent.com/46134462/148934442-a8b4a5ed-6c91-45cd-9caa-bda05697fe18.png)

Text channel/User mention menu in chat
![image](https://user-images.githubusercontent.com/46134462/148934649-f86feb0c-ebc7-4d25-b5e2-d2ebaf8de1fe.png)

Better Discord version in the Discord Versions section of settings is black, as is the titles of better discord settings menus
![image](https://user-images.githubusercontent.com/46134462/148934766-623b2553-29a1-4b0c-9aea-9026d63f9ef2.png)
![image](https://user-images.githubusercontent.com/46134462/148934848-4fbc4163-8d2c-4bde-a26e-db5baa49a8fa.png)

Discord Changelog reverted to default Discord grey
![image](https://user-images.githubusercontent.com/46134462/148934936-3562c5e9-451b-45f3-85b8-c0f82acd8086.png)

**Versions :**
 - Theme style : Dark
 - Theme version : 3.0.5
 - Discord Version : Stable 110451 (c233a73)
 - BDD version : 1.3.0

**Comment by orblazer** [comment]
Hello,
This theme haven't receive update from long time and discord have broke a lot of stuff recently :disappointed: 

I go to remake that theme soonly.

**Comment by orblazer** [comment]
Hello,
I keep this issue for now but the version `3.1.0` should fix a lot of issues

**Comment by orblazer** [comment]
I thinks almost all is fixed, so i go to close this issue.
